database/factories/UserFactory.php, database/seeders/UserSeeder.php
=> ✨ feat(seeders): UserSeeder

database/seeders/UserSeeder.php, storage/app/private/fake_seed_data/users.json
se agregan usuarios fijos para userseeder desde archivo json
=> Seeder users

app/Http/Controllers/Api/CartItemController.php, app/Http/Controllers/Api/FavoriteController.php, app/Http/Controllers/Api/FavoriteListController.php, app/Http/Requests/CartItems/IndexRequest.php, app/Http/Requests/CartItems/StoreRequest.php, app/Http/Requests/CartItems/UpdateRequest.php, app/Http/Requests/FavoritesList/StoreRequest.php, app/Http/Requests/FavoritesList/UpdateRequest.php, app/Http/Resources/CartItems/CartItemCollection.php, app/Http/Resources/CartItems/CartItemResource.php, app/Http/Resources/Favorites/FavoriteResource.php, app/Http/Resources/FavoritesList/FavoriteListCollection.php, app/Http/Resources/FavoritesList/FavoriteListResource.php, database/migrations/2025_06_03_162206_add_unit_to_cart_items_table.php
actualizacion endpoints Carrito
se agrega columna "unit" para proceso de ordenes de compra
=> Fix carrito

app/Http/Resources/Products/ProductCollection.php
Se envia el request de los filtros al ProductCollection
=> fix: rango precios se envia request al collection

app/Http/Controllers/AuthController.php, app/Models/User.php, database/seeders/RolesAndPermissionsSeeder.php
se agrega seeder de permisos y roles
asignacion a usuarios
agregar al json de respuesta token 
"roles": [
"colaborador"
],
"permissions": [
"can-see-own-purchases",
"can-see-all-products",
"can-edit-content"
]
=> feat: agregar permisos y role

database/seeders/RolesAndPermissionsSeeder.php
crear roles segun listado 
asignar a usuarios
seeder modificado
=> modificar seed de roles y permisos, asignar a usuarios

tests/Feature/PersonalInformationTest.php
Las pruebas de usuario estan bien, pero fallan otras.
Considerar para revisar @prodev443
=> test:  #98 -  agrega pruebas para la creación de usuario

app/Models/Product.php, database/factories/MunicipalityFactory.php, database/seeders/DatabaseSeeder.php, database/seeders/RolesAndPermissionsSeeder.php, tests/Feature/ProductTest.php
complementar test de productos, busquedas.
issue 88 
#88 
correcion al seeder de  permisos (error en la ejecucion del seed)
=> agregar test para productos

database/seeders/RolesAndPermissionsSeeder.php, tests/Feature/AddressTest.php
Correccion test (elimina estructura json no es necesario)
Modificar permiso rol cliente .
=> fix: corregir test user addresslist , y permisos

app/Http/Controllers/Api/CartController.php, app/Http/Controllers/Api/CartItemController.php, app/Models/User.php, routes/api.php, tests/Feature/CartItemTest.php
#134 
Vaciar carrito
#133  Ordenar lista carrito por id
=> vaciar carrito

app/Http/Controllers/Api/AddressController.php, app/Http/Requests/Addresses/StoreRequest.php, app/Http/Requests/Addresses/UpdateRequest.php, app/Http/Resources/Addresses/AddressResource.php, app/Models/Address.php, database/migrations/2025_06_16_201824_add_alias_to_addresses_table.php, tests/Feature/AddressTest.php
=> agregar alias a direcciones, modificar resultado json

app/Http/Controllers/Api/UserController.php, app/Http/Resources/Users/UserCollection.php, app/Models/User.php, routes/api.php, tests/Feature/UserTest.php
Revisar este punto: https://github.com/Socomarca/socomarca-backend/commit/ee8e1d6b6428bd479bb4663ccd332c6e37ee53c1#r160276326
---
Esta *pull request* introduce una nueva funcionalidad de búsqueda de usuarios con capacidades de filtrado y ordenamiento, actualiza el recurso `UserCollection` para proporcionar una estructura de usuario detallada, y añade pruebas exhaustivas para asegurar la correcta implementación de las nuevas características. Los cambios más importantes incluyen la adición del endpoint de búsqueda, la implementación de la lógica de filtrado y ordenamiento, y la creación de pruebas para validar la nueva funcionalidad.
* **Endpoint de búsqueda**: Se añadió el método `search` en `UserController` para permitir la búsqueda de usuarios mediante filtros y paginación. El endpoint …
=> feat: #149 - Agrega funcionalidad de búsqueda y filtrado de usuarios 

app/Http/Controllers/Api/FavoriteController.php, app/Http/Requests/Favorites/StoreRequest.php, app/Http/Resources/Favorites/FavoriteResource.php, app/Http/Resources/FavoritesList/FavoriteListResource.php, app/Models/Favorite.php, app/Rules/ProductHasUnit.php, database/factories/FavoriteFactory.php, database/migrations/2025_06_18_120842_add_unit_to_favorites.php, tests/Feature/FavoriteTest.php
=> fix: favoritos json actualizado

app/Http/Controllers/Api/FaqController.php, app/Http/Requests/Faq/DestroyRequest.php, app/Http/Requests/Faq/SearchRequest.php, app/Http/Requests/Faq/StoreRequest.php, app/Http/Requests/Faq/UpdateRequest.php, app/Http/Resources/Faq/FaqCollection.php, app/Http/Resources/Faq/FaqResource.php, app/Models/Faq.php, database/factories/FaqFactory.php, database/migrations/2025_06_20_132726_create_faqs_table.php, database/seeders/DatabaseSeeder.php, database/seeders/FaqSeeder.php, database/seeders/RolesAndPermissionsSeeder.php, routes/api.php, tests/Feature/FaqTest.php
Esta *pull request* introduce un sistema completo de gestión de preguntas frecuentes (FAQ), que incluye la creación de un nuevo modelo `Faq`, endpoints de API, validación de solicitudes, clases de recursos, migraciones de base de datos, fábricas y *seeders*. Los cambios permiten operaciones CRUD y capacidades avanzadas de búsqueda y filtrado para FAQs.
* Se añadió el `FaqController` con métodos para listar, crear, obtener, actualizar, eliminar y buscar FAQs. El controlador integra validación de solicitudes y transformación de recursos para respuestas API consistentes.
* Se actualizó `routes/api.php` para registrar el `FaqController` en el enrutamiento de la API.
* Se añadieron las clases `DestroyRequest`, `SearchRequest`, `StoreRequest` y `UpdateRequest` para validar entradas en …
=> Feat: CRUD para la gestión de FAQs

README.md, app/Http/Controllers/Api/UserController.php, app/Http/Requests/AuthRequest.php, app/Http/Requests/Users/DestroyRequest.php, app/Http/Requests/Users/StoreRequest.php, app/Http/Requests/Users/UpdateRequest.php, app/Http/Resources/Users/UserResource.php, app/Mail/UserNotificationMail.php, app/Models/User.php, app/Rules/ValidateRut.php, resources/views/emails/user-notification.blade.php, routes/api.php, tests/Feature/AdminUserTest.php
Esta *pull request* introduce actualizaciones importantes en el `UserController` y componentes relacionados para mejorar la funcionalidad de gestión de usuarios, incluyendo mejoras en la validación, operaciones transaccionales, asignación de roles y notificaciones por correo electrónico. Los cambios también incluyen nuevos métodos auxiliares y recursos para un mejor manejo de los datos de usuarios.
* **Operaciones transaccionales para creación y actualización de usuarios**: Se añadieron transacciones de base de datos en los métodos `store`, `update` y `destroy` del `UserController` para asegurar la consistencia de los datos. [\[1\]](diffhunk://#diff-aa08cd8c325dc99507b40416ba12d4e35e1e9e892e75efa568e1bc0b58a16b81L29-R104) [\[2\]](diffhunk://#diff-aa08cd8c325dc99507b40416ba12d4e35e1e9e892e7 …
=> CRUD para el administrador de usuarios

app/Http/Resources/Favorites/FavoriteResource.php
Esta *pull request* refactoriza el método `toArray` en la clase `FavoriteResource` para mejorar la eficiencia y legibilidad del código, reduciendo las consultas repetidas a la base de datos. Los cambios más importantes implican centralizar la obtención de datos relacionados con el precio de un producto según la unidad.
* [`[app/Http/Resources/Favorites/FavoriteResource.php](diffhunk://#diff-d03721afd5c16b1987f17f625fd2324addc38d40d81aeb6ac36660d13b652138R21-R23)`](diffhunk://#diff-d03721afd5c16b1987f17f625fd2324addc38d40d81aeb6ac36660d13b652138R21-R23): Se introdujo una nueva variable `$priceData` para almacenar la primera entrada de precio que coincida con la unidad del favorito, evitando llamadas repetidas a la base de datos para obtener los valores de `unit`, `price` y `stock`.
* …
=> Refactoriza la obtención de datos de precios en FavoriteResource para mejorar la legibilidad y eficiencia del código.

app/Http/Controllers/Api/ProductController.php, app/Http/Resources/Products/ProductCollection.php, app/Models/Product.php, routes/api.php, tests/Feature/ProductTest.php
Refactor busqueda productos, filtros rango precio, mantener en la busqueda (obligatorios)
opcionales : unit ,  categorie, subcat, name, favorite.  explicacion en insomnia
test modificados
=> refactor busqueda por producto filtros, test

app/Http/Controllers/Api/AddressController.php, app/Http/Requests/Addresses/PatchRequest.php, database/migrations/2025_06_25_174900_add_status_to_municioalities_table.php, database/seeders/RegionSeeder.php, routes/api.php
=> modifacion parcial direccion, seeder modificados, regiones, comunas

app/Http/Controllers/Api/ReportController.php
Se requería mejorar el método `clientsList()` del sistema de reportes para:
1. **Mostrar información geográfica**: Agregar el nombre de la región y el municipio de cada orden
2. **Nuevo filtro**: Permitir filtrar órdenes por código de región
- **Problema**: Las órdenes solo mostraban datos básicos (ID, cliente, monto, fecha, estado)
- **Solución**: Se agregó la capacidad de mostrar el nombre del municipio y la región donde se realizó cada orden
- **Datos Extraídos**: Se obtiene el `municipality_id` del JSON almacenado en `order_meta` y se consultan los nombres correspondientes
- **Problema**: No se podía filtrar las órdenes por ubicación geográfica
- **Solución**: Se agregó un nuevo parámetro `region` que permite filtrar por código de región (ejemplo: "09" para La Araucanía)
- …
=> feat: #212 - Agregar filtro opcional por región en el listado de clientes y mejorar la obtención de municipios y regiones en los reportes.

app/Http/Controllers/Api/ReportController.php, app/Http/Controllers/Api/UserController.php, routes/api.php
#211 
listado de clientes sin parametros, sin filtros, sin paginacion.
=> endpoint get listado de clientes

app/Http/Controllers/Api/AddressController.php, app/Http/Controllers/Api/UserController.php, app/Models/Municipality.php, app/Models/Region.php, routes/api.php, tests/Feature/AddressTest.php, tests/Feature/UserTest.php
-  **PATCH** `/municipalities/status` - Actualización masiva de status de municipios
-  **PATCH** `/regions/{region}/municipalities/status` - Actualización de región y todas sus comunas
-  Middleware de permisos `role:admin|superadmin` en endpoints de actualización
-  Validaciones completas y manejo de errores
-  **PATCH** `/users/{id}` - Actualización parcial de campos de usuario
-  Validaciones con `sometimes` para campos opcionales
-  Hash automático de contraseñas con confirmación
-  Protección con `role:admin|superadmin` en endpoints críticos
-  Validación de permisos para operaciones administrativas
-  Tests para **PUT** y **PATCH** de direcciones
-  Test de actualización masiva de municipios
-  Test de actualización de región y sus municipios
-  Tests de validación y permisos
- …
=> feat: endpoints comunas regiones usuarios, test

app/Http/Controllers/Api/AddressController.php, tests/Feature/AddressTest.php
generar json con la info de la nueva direccion
=> feat: agregar info  en la respuesta

app/Http/Controllers/Api/CartItemController.php, tests/Feature/CartItemTest.php
modificacion de controller y test
=> refactor cartitem

app/Providers/AppServiceProvider.php, composer.json, composer.lock, config/mail.php, config/services.php
=> Adds Brevo Mailer support

app/Exports/OrdersReportExport.php, app/Http/Controllers/Api/ReportController.php, routes/api.php
**Export general de órdenes a Excel**
- Endpoint: POST /api/orders/reports/export
- Archivo generado: OrdersReportExport.php
- Funcionalidad dual:
- Con cliente: Agrupa por fecha Y cliente específico
- Sin cliente: Agrupa solo por fecha (todos los clientes)
- Columnas: fecha, cliente, monto
- Nombre archivo: reporte_ordenes_YYYY-MM-DD_HH-mm-ss.xlsx
=> feat: #238 - Descarga de datos para el reporte del total de ventas

app/Http/Controllers/Api/SiteinfoController.php, tests/Feature/SiteinfoTest.php
#281 
correccion al actualizar sin imagenes
agregar a la respuesta get  "message enabled"
correccion test
=> fix concatenar imagenes, agregar message enabled en la respuesta GET

app/Http/Controllers/Api/PriceExtremesController.php, app/Http/Controllers/Api/ProductController.php, routes/api.php, tests/Feature/BrandTest.php, tests/Feature/CategoryTest.php, tests/Feature/ExportsTest.php, tests/Feature/Http/Controllers/PriceControllerTest.php, tests/Feature/Http/Controllers/PriceExtremesControllerTest.php, tests/Feature/PaymentMethodTest.php, tests/Feature/ReportsTest.php, tests/Feature/SubcategoryTest.php
=> refactor: Actualiza permisos y nombres de rutas para métodos de pago

.env.example, app/Http/Resources/Products/ProductCollection.php, app/Jobs/SyncProductImage.php, config/filesystems.php
de imagen para productos en la colección
feat(SyncProductImage): actualiza la asignación de imagen del producto a la ruta de S3
=> feat(ProductCollection): actualiza la generación de URL 
